version: '3'
services:
  mongodb:
    image: mongo
    container_name: my-mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: localhost
      MONGO_INITDB_ROOT_PASSWORD: 18er0821
    volumes:
      - './data:/data/db'
